name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pybind11-dev python3-dev python3-pip python3-setuptools python3-wheel
    
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: CMake Action
      uses: threeal/cmake-action@v2.0.0

    - name: Download test file
      run: wget -P build/tests https://huggingface.co/karpathy/tinyllamas/resolve/main/stories15M.bin
    
    - name: Create symlink for tokenizer.bin
      run: cp tokenizer.bin build/tests/tokenizer.bin

    - name: Run tests
      run: ctest --test-dir build --rerun-failed --output-on-failure 